on:
  push:
  # branches: [master]
  pull_request:

name: CI
jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --also=dev
        working-directory: pack-flatpak-and-upload-to-github-release-tag
      - run: yarn test
        working-directory: pack-flatpak-and-upload-to-github-release-tag
