on:
  release:
    types: [created]

jobs:
  deploy-javascript-action:
    name: Deploy Javascript Action
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Publish action
        uses: github-actions-publish/publish-action@v1
        with:
          tag: v1